Team commendations
CreativeSolutionsGroup/bz-commendations-next pull request #89
Opened 2023-02-28 01:16 UTC by awtpi314

Closes #84 

Adds team commendation page implementation.

2023-02-28 03:12 UTC, SpBills approved these changes
Some general info-

Great work overall Alex! You did a really good job at making the business requirements work. There are some general architectural things.

1. You should *never* trust the client. Someone could send a bunch of emails, and it would send them without checking. (maybe? maybe not? either way, never trust the client to provide its own emails. we prefer sending the ids instead.)
2. Great job in general with the creating new functions.
3. We are trying to stay consistent with `camelCase` for functions and variables, and  `PascalCase` for components.
4. I wonder if it was necessary to make an entirely new component for the team commendation, and if we could have simply reused the single commendation. Nothing you have to change, just something to think about.

Overall, very good job. I am only criticizing because your work is very well done and I think you do a very good job at taking criticism and applying it. I hope this helps in the same way that you teaching me things about Prisma helped me. in past PRs.

2023-02-28 03:12 UTC, SpBills commented on lib/api/commendations/email.ts
> +export const send_bz_email = async (
change to `sendBzEmail`

2023-02-28 03:12 UTC, SpBills commented on pages/api/commendation/index.ts
> +        const commendation = await createCommendation(sender as string, await emailToId(recipient) ?? "", msg);
do we really get a list of emails from the frontend? we should not be getting a list of emails from the frontend.

2023-02-28 03:12 UTC, SpBills commented on pages/api/commendation/index.ts
> +        const commendation = await createCommendation(sender as string, await emailToId(recipient) ?? "", msg);
i guess it doesn't really matter?

2023-02-28 03:12 UTC, SpBills commented on components/TeamCommendationForm.tsx
> +              return currentMember.email;
send ids instead.

2023-02-28 03:12 UTC, SpBills commented on lib/api/commendations/crud.ts
> +    studentIds.map((currentId) => prisma.member.findFirst({ where: { id: currentId } }))))
Do this as a bulk query instead of mapping in memory?

2023-02-28 03:13 UTC, SpBills requested changes
oops, didn't mean to approve quite yet.

2023-03-01 20:08 UTC, SpBills requested changes
mmm. much better. just a tiny change

2023-03-01 20:08 UTC, SpBills commented on lib/api/teams/crud.ts
> +    const member = await prisma.member.findFirst({
better hope that a member ID and a team ID never overlap.

2023-03-01 20:08 UTC, SpBills commented on lib/api/teams/crud.ts
> +        team.members.forEach((currentMember) => {
You should use map syntax instead here.

map takes `[T]` and turns it into type `[U]`, or in this case `[Member]` into `[string]`

yes, this means you'll have to do 2 separate maps.

2023-03-01 20:14 UTC, awtpi314 commented on lib/api/teams/crud.ts
> +    const member = await prisma.member.findFirst({
uuid cool

2023-03-27 11:58 UTC, merged